// <auto-generated />
using Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Domain.Entities.CitySetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FreeMonthList")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximunFeePerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumTimeCalcuteFee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("CitySetting");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FreeMonthList = "[7]",
                            MaximunFeePerDay = 60,
                            MinimumTimeCalcuteFee = 60,
                            Name = "Gothenburg"
                        },
                        new
                        {
                            Id = 2,
                            MaximunFeePerDay = 80,
                            MinimumTimeCalcuteFee = 30,
                            Name = "London"
                        });
                });

            modelBuilder.Entity("Domain.Entities.HourFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("End")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeeAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<long>("Start")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HourFee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            End = 233400000000L,
                            FeeAmount = 8,
                            Start = 216000000000L
                        },
                        new
                        {
                            Id = 2,
                            End = 251400000000L,
                            FeeAmount = 13,
                            Start = 234000000000L
                        },
                        new
                        {
                            Id = 3,
                            End = 287400000000L,
                            FeeAmount = 18,
                            Start = 252000000000L
                        },
                        new
                        {
                            Id = 4,
                            End = 305400000000L,
                            FeeAmount = 13,
                            Start = 288000000000L
                        },
                        new
                        {
                            Id = 5,
                            End = 539400000000L,
                            FeeAmount = 8,
                            Start = 306000000000L
                        },
                        new
                        {
                            Id = 6,
                            End = 557400000000L,
                            FeeAmount = 13,
                            Start = 540000000000L
                        },
                        new
                        {
                            Id = 7,
                            End = 611400000000L,
                            FeeAmount = 18,
                            Start = 558000000000L
                        },
                        new
                        {
                            Id = 8,
                            End = 647400000000L,
                            FeeAmount = 13,
                            Start = 612000000000L
                        },
                        new
                        {
                            Id = 9,
                            End = 665400000000L,
                            FeeAmount = 8,
                            Start = 648000000000L
                        },
                        new
                        {
                            Id = 10,
                            End = 215400000000L,
                            FeeAmount = 0,
                            Start = 666000000000L
                        });
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = 4,
                            VehicleType = 6
                        },
                        new
                        {
                            Id = 5,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = 6,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = 7,
                            VehicleType = 7
                        },
                        new
                        {
                            Id = 8,
                            VehicleType = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
